spring.application.name=flood-rescue-system

# Chú ý: ph?i là jdbc:postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/flood_rescue_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

app.jwt.secret=0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF
app.jwt.access-expiration=900000
app.jwt.refresh-expiration=604800000